spring:
  datasource:
    url: jdbc:mysql://www.91iedu.com:3391/team04?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: team04
    password: team04
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.iedu.demo.doubandemo.entity

logging:
  level:
    com.tgu.team04.analysis.dao: debug
