spring:
  datasource:
    url: jdbc:mysql://www.91iedu.com:3391/team04?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: team04
    password: team04
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource